// @flow

import {
  PRIMARY,
  BLACK,
  WHITE,
  GREY_DARK,
  PRIMARY_DARK,
  GREY_LIGHTER,
  SECONDARY,
} from './colors';

export const COLORS = {
  PRIMARY,
  BLACK,
  WHITE,
  GREY_DARK,
};

export const BACKGROUND_COLORS = {
  WHITE,
  PRIMARY,
  PRIMARY_DARK,
  GREY_LIGHTER,
  SECONDARY,
};

const LIGHT_BACKGROUND = {
  default: COLORS.BLACK,
  highlight: COLORS.PRIMARY,
};

export const COLORS_FOR_BACKGROUND = {
  [BACKGROUND_COLORS.WHITE]: LIGHT_BACKGROUND,
  [BACKGROUND_COLORS.PRIMARY]: {
    default: COLORS.BLACK,
  },
  [BACKGROUND_COLORS.PRIMARY_DARK]: {
    default: COLORS.WHITE,
  },
  [BACKGROUND_COLORS.GREY_LIGHTER]: LIGHT_BACKGROUND,
  [BACKGROUND_COLORS.SECONDARY]: {
    default: COLORS.BLACK,
  },
};
